### ISSUE TITLE
Clicking "Today" doesn't take you to today (or anywhere).

### ISSUE THREAD

**Issue by MatthewJMullins** [liamcain/obsidian-calendar-plugin#212] opened 2021-11-18 13:20 UTC

**Comment by liamcain** [comment] 2021-11-21 20:46
Hi, the "Today" button will reset the view to show the current month. It's useful if you're navigating around to view a different day from a few months ago, then you can click "Today" to quickly jump the calendar back to the current month.

**Comment by liamcain** [comment] 2021-11-21 20:47
Going to close this issue since it's not a bug, but in the v2 Beta of the calendar plugin (available from [Github Releases](https://github.com/liamcain/obsidian-calendar-plugin/releases/tag/2.0.0-beta.2), I've changed the text "Today" to a dot to avoid confusion.

**Closed by liamcain** 2021-11-21 20:47 UTC
Labels: bug

**Comment by nbarman2022** [comment] 2022-02-22 18:48
I actually really like having the word "today" there, but it would be better if clicking "today" actually caused the daily note for today's date to become the primary page on the screen.
