### ISSUE TITLE
Plugin does not appear on Ipad Pro

### ISSUE THREAD

**Issue by DanielYehezkeli** [liamcain/obsidian-calendar-plugin#246] opened 2022-04-30 23:10 UTC
### Describe the bug
I've been setting up obsidian on Ipad Pro and even after re-installing and re-enabling It does not appear on the pulled window on the right.

**Comment by apgdjr** [comment] 2022-08-14 17:18
Is this a open and recon issue?

**Comment by uwe999** [comment] 2022-10-29 02:53
Thanks, that's not very intuitive but it worked

**Comment by mattitanskane** [comment] 2023-01-05 14:11
Tested on iPadOS 16.2 and iOS 16.2, calendar works on both. Not a bug but more a UX inconvenience just like @uwe999 pointed out. 

@DanielYehezkeli could you close the issue?

**Comment by Xtremefaith** [comment] 2023-05-03 19:46
At one point I believe this was pinned similar to the desktop version but then I accidentally dragged it off the sidebar and now I'm stuck with the implementation mentioned above. Is there not a way to get it pinned back? For example there are separate sections on the desktop view, it would be great if this was restored some how.
<img width="228" alt="image" src="https://user-images.githubusercontent.com/1228550/236030080-188ce30b-138c-417e-bb17-ef75012153da.png">

**Comment by MarkOSullivan94** [comment] 2023-06-03 15:08
Firstly, thank you for the hard work on an amazing plugin! Love it and found it has greatly enhanced my experience using Obsidian.

Would be great if this would work similar to how it works on Desktop

I find it annoying having to use the Expand icon instead of having multiple icons at the top which I can tap on

Alternatively is there shortcuts to open Backlinks view and Calendar view? That might work for me for now.

**Closed** 2023-06-20 21:56 UTC
Labels: bug
