### ISSUE TITLE
Does not recognize daily note folder

### ISSUE THREAD

**Issue by lillianhorin** [liamcain/obsidian-calendar-plugin#14] opened 2020-10-30 19:12 UTC
OS: Windows 10

I have a daily note folder to keep my daily notes away from the main pane. However the plugin isn't recognizing it. It will only recognize daily notes that are in the main folder. When I make a daily note thru the app and then move it, it also breaks the recognition and says it doesn't exist.

**Comment by liamcain** [comment] 2020-10-30 21:02
Hi @lillianhorin, what do you have as your "New Note Location" in `Settings > Daily Note`?

<img width="962" alt="image" src="https://user-images.githubusercontent.com/693981/97756645-98dc6600-1ad1-11eb-8fb7-d01bf82b3f5b.png">


The calendar will only recognize notes placed in that directory.

**Comment by ashleyhindle** [comment] 2020-10-30 21:55
This happens to me also on Windows 10

These are my Daily notes settings & other info:
![image](https://user-images.githubusercontent.com/454975/97760277-a9550680-1afa-11eb-896b-6414eb739b91.png)

![image](https://user-images.githubusercontent.com/454975/97760254-9e9a7180-1afa-11eb-83ed-a5bd1332c355.png)

![image](https://user-images.githubusercontent.com/454975/97760238-96dacd00-1afa-11eb-87fd-34972aa9237b.png)

**Comment by akicebear** [comment] 2020-10-31 03:20
I am also having this issue. I have the Daily Notes setup to put new daily notes in "01 Notes", with title format "YYYY-MM-DD". When I use this plugin it simply creates new notes in the main folder.

**Comment by liamcain** [comment] 2020-10-31 06:39
This should be fixed now in version 1.1.0. Please let me know if you're still seeing this issue after updating!

**Comment by AJP4** [comment] 2020-10-31 07:53
Hi, I have the same issue.  I try to create a new day note in the future and the create button is not responsive.  All folders and template locations are good.  I'm on obsidian v9.10

**Comment by akicebear** [comment] 2020-10-31 14:01
Unfortunately now the plugin fails to install via the settings menu

**Comment by wouterbo** [comment] 2020-10-31 15:58
Version 1.3.1 fixes the problem for me.

**Comment by liamcain** [comment] 2020-10-31 16:14
This should finally be resolved in v1.1.3. Sorry for the earlier confusion!

**Closed by liamcain** 2020-10-31 16:14 UTC

**Comment by ashleyhindle** [comment] 2020-10-31 16:30
Excellent, thanks so much!

This is an awesome plug-in, glad you made it 😄

**Comment by akicebear** [comment] 2020-10-31 16:48
The issue is resolved for me too - thanks!

**Comment by lillianhorin** [comment] 2020-10-31 16:58
Apologies for not getting to your question earlier! And it's all fixed for
me now too. Thank you!

Best wishes,
*Lillian Horin*
Ph.D Student, Harvard University
Pronouns: she, her, hers
Website <http://lillianhorin.com>

**Comment by lillianhorin** [comment] 2020-10-31 16:58
Apologies for not getting to your comment sooner! It is all resolve for me. Thanks for the great plugin!
